version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    container_name: elysia-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elysia-api
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${WS_PORT}:${WS_PORT}
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
    driver: local
