export enum MESSAGES_EVENTS {
  NEW_MESSAGE = "MESSAGES:NEW_MESSAGE",
}

export enum TASKS_EVENTS {
  TASK_CREATED = "TASKS:TASK_CREATED",
  TASK_DELETED = "TASKS:TASK_DELETED",
}

export enum CHATS_EVENTS {
  NEW_CHAT = "CHATS:NEW_CHAT",
}
